### ISSUE TITLE
Nothing happens after DNS initialization

### ISSUE THREAD

**Issue by Marvo995** [Gannio/Shiny2-and-a-Half#2]
Forwared the 80 TCP and 53 UDP ports, set my local ip and altserverip (that is kaeru's server ip 178.62.43.212), saved settings, click initialize dns and nothing happens. According to a guide I found on reddit after the initial dns initialization I have to change the altserver ip with the local one and a dns test should start. I did that as well, but the test won't run. In addition when I restart the app the ip adresses lose their dots and if i try to start a DNS initialization the app will close itself (is it a crash?)

**Comment by Gannio** [comment]
Currently online is broken to some degree it seems (sorry I took so long to respond, I had to take a while to get the means to test online connections again). Have you been able to get it to work with your local IP address rather than your online one? In the first version the terminology was a bit confusing, so the current source has a Detect IP (LAN) button that should perform local IP detection for you, and the instructions have been cleared up somewhat, so hopefully it should be easier to understand.
